version: '3.3'

services:
 php:
  image: abdelilahmhamdi/mhamdi_pdo_mysql:latest
  container_name: php_pdo_mysql
  depends_on:
   - db
  volumes:
   - ./php:/var/www/html/
  ports:
   - 8092:80
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: mhamdidb
   MYSQL_USER: mhamdi
   MYSQL_PASSWORD: password
  ports:
   - 3306:3306
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   PMA_USER: mhamdi
   PMA_PASSWORD: password
   UPLOAD_LIMIT: 20M
  ports:
   - 8899:80
